modules:

  #
  # Module which pulls data from various twitter users and stores it in db.
  #
  twitter:

    # Twitter authentication details.
    # See https://apps.twitter.com/
    auth:
      oauthAccessTokenSecret:
      oauthAccessToken:
      oauthConsumerSecret:
      oauthConsumerKey:

    # How often to pull data from each user.
    intervalMillis: 60000

    # Users to pull data from.
    users: [
      shitpostbot5000
    ]

  #
  # Module which forwards data to discord.
  #
  discord:

    # How often to try to send the data.
    intervalMillis: 1000

    # Discord app authentication details.
    # See https://discordapp.com/developers/applications/me
    auth:
      token:

    # Which channels to send data to.
    channels: [
      general
    ]

  #
  # Testing module which prints data from db to console.
  #
  printing:
    intervalMillis: 1000

# Thread configuration, tweak according to system resources and desired performance.
executors:
  poolSize: 2

# Database path which is used to store data.
db:
  path: data.db