modules:

  # Twitter module pulls data from various twitter users and stores it in db.
  twitter:

    # Twitter developer authentication keys.
    auth:
      oauthAccessTokenSecret:
      oauthAccessToken:
      oauthConsumerSecret:
      oauthConsumerKey:

    # How often to pull data from each user.
    intervalMillis: 60000

    # Users to pull data from.
    users: [
      shitpostbot5000
    ]

  # Simple module used for testing purposes.
  printing:
    intervalMillis: 1000

  # Module which forwards memes to discord.
  discord:

    # How often to try and send the memes.
    intervalMillis: 1000

    # Discord app authentication details.
    auth:
      token:

    # Which channels to send messages to.
    channels: [
      general
    ]

# Thread configuration, tweak according to system resources and desired performance.
executors:
  poolSize: 2

# Database path which is used to store memes.
db:
  path: data.db