modules:

  # Twitter module pulls data from various twitter users and stores it in db.
  twitter:
    auth:
      oauthAccessTokenSecret:
      oauthAccessToken:
      oauthConsumerSecret:
      oauthConsumerKey:
    users: [
      shitpostbot5000
    ]

# Thread executor configurations, tweak according to system resources and desired performance.
executors:
  producers:
    poolSize: 2
  consumers:
    poolSize: 2

# Database path, which is used to store data during and after application shutdowns.
db:
  path: data.db